# Generated by Django 5.2.8 on 2025-11-19 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_post_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='consistency_family',
        ),
    ]
